### PR TITLE
feat: Add new locales

### PR DESCRIPTION
**Pull request by AliMehraei**
de, fr, it : translated by deepl.com
zh: translated by google.
These locale translations will be updated by native translators during days ahead.

### CODE REVIEW

**Comment by AliN11** [comment]
Thank you for your efforts. A question: Are these translations incomplete? Since you said that they are going to be updated.

**Comment by AliMehraei** [comment]
> Thank you for your efforts. A question: Are these translations incomplete? Since you said that they are going to be updated.

Hi , No theses translations are correct and we using them in our project now, but we asked the native people to improve each locale translations. so we will apply the improvements continuously.

**Comment by AliN11** [comment]
> Hi , No theses translations are correct and we using them in our project now, but we asked the native people to improve each locale translations. so we will apply the improvements continuously.

Thank you again @AliMehraei. Since these translations are produced by a translator (not a native speaker), we cannot completely guaranty their accuracy. So we cannot merge this pull request for now unfortunately.

**Comment by AliN11** [comment]
Thank you. Merged and new version 1.8.0 released and is available on npm.

**Pull request merged**
